but no error was thrown
